from typing import Dict, Any, List
import json
import zipfile
import io

def generate_repository_files(prompt: str, intent: Dict[str, Any], genomes: Dict[str, Any], apis: Dict[str, Any], db: Dict[str, Any], ui: Dict[str, Any]) -> Dict[str, str]:
    """
    Compile a dictionary representing the codebase structure: { filepath: content }
    """
    title = intent["title"]
    domain = intent["domain"]
    tagline = intent["tagline"]
    
    # 1. README.md
    readme = f"""# {title}

> {tagline}

This software system was synthesized by the **Reverse Software Search (RSS)** engine from the request:
`"{prompt}"`

Category: **{domain}**

---

## 🛠️ Synthesized Tech Stack
- **Frontend**: Next.js 14 (App Router), React, TypeScript, TailwindCSS
- **Backend**: FastAPI (Python 3.10+), SQLAlchemy
- **Message Broker & Caching**: Redis
- **Database**: SQLite (default developer) / PostgreSQL (production scaling)

---

## 🚀 Getting Started

### Prerequisites
- Python 3.10+
- Node.js 18+
- Docker & Docker Compose (optional)

### Local Dev Setup

#### 1. Backend API (FastAPI)
```bash
cd backend
python -m venv venv
source venv/bin/activate # On Windows: venv\\Scripts\\activate
pip install -r requirements.txt
uvicorn main:app --reload --port 8000
```
The interactive Swagger API documentation will be active at: http://localhost:8000/docs

#### 2. Frontend client (Next.js)
```bash
cd frontend
npm install
npm run dev -- --port 3000
```
Open http://localhost:3000 to interact with the UI dashboard.

---

## 🐳 Docker Deployment (Optional)
To run the entire system (Frontend, Backend, Redis cache) in one command:
```bash
docker-compose up --build
```
"""

    # 2. docker-compose.yml
    docker_compose = """version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./app.db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
"""

    # 3. Backend Dockerfile
    backend_dockerfile = """FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
"""

    # 4. Backend requirements.txt
    backend_reqs = """fastapi==0.111.0
uvicorn==0.30.1
sqlalchemy==2.0.31
pydantic==2.7.4
python-multipart==0.0.9
redis==5.0.6
"""

    # 5. Backend main.py
    backend_main = f"""# Autogenerated FastAPI service for {title}
from fastapi import FastAPI, Depends, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
import json

app = FastAPI(
    title="{title} API Engine",
    description="Synthesized backend endpoints for {tagline}",
    version="1.0.0"
)

# CORS configuration
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
def read_root():
    return {{"status": "online", "system": "{title}", "description": "{tagline}"}}

@app.get("/api/v1/health")
def health_check():
    return {{"status": "healthy"}}

# Simple WS room management
class ConnectionManager:
    def __init__(self):
        self.active_connections: list[WebSocket] = []

    async def connect(self, websocket: WebSocket):
        await websocket.accept()
        self.active_connections.append(websocket)

    def disconnect(self, websocket: WebSocket):
        self.active_connections.remove(websocket)

    async def broadcast(self, message: str):
        for connection in self.active_connections:
            await connection.send_text(message)

manager = ConnectionManager()

@app.websocket("/ws/room/{{room_id}}")
async def websocket_endpoint(websocket: WebSocket, room_id: str):
    await manager.connect(websocket)
    try:
        while True:
            data = await websocket.receive_text()
            # Broadcast edit events to all active editors in workspace room
            await manager.broadcast(json.dumps({{
                "room": room_id,
                "payload": data,
                "sender": "peer"
            }}))
    except WebSocketDisconnect:
        manager.disconnect(websocket)
"""

    # 6. Frontend package.json
    frontend_package = """{
  "name": "frontend-workspace",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "next": "^14.2.3",
    "lucide-react": "^0.395.0",
    "tailwindcss": "^3.4.3"
  },
  "devDependencies": {
    "typescript": "^5.4.5",
    "@types/node": "^20.14.2",
    "@types/react": "^18.3.3"
  }
}
"""

    # 7. Frontend Layout Component
    frontend_page = f"""// Autogenerated view for {title}
import React from 'react';

export default function SynthesizedHome() {{
  return (
    <div style={{{{ 
      fontFamily: 'system-ui, sans-serif', 
      padding: '40px', 
      maxWidth: '800px', 
      margin: '0 auto',
      backgroundColor: '#0a0a0a',
      color: '#ffffff',
      borderRadius: '12px',
      marginTop: '50px',
      boxShadow: '0 4px 30px rgba(0, 0, 0, 0.5)',
      border: '1px solid #1f1f1f'
    }}}}>
      <h1 style={{{{\n        backgroundImage: 'linear-gradient(to right, #00c4cc, #8b5cf6)',\n        WebkitBackgroundClip: 'text',\n        WebkitTextFillColor: 'transparent',\n        fontSize: '3rem'\n      }}}}>{title}</h1>
      <p style={{{{ fontSize: '1.25rem', color: '#a0a0a0', marginBottom: '30px' }}}}>
        {tagline}
      </p>
      
      <div style={{{{ border: '1px solid #2f2f2f', borderRadius: '8px', padding: '20px', backgroundColor: '#121212' }}}}>
        <h3>🚀 Synthesized Features Included:</h3>
        <ul>
          <li>Real-time socket synchronization pipelines</li>
          <li>PostgreSQL relational table schemas</li>
          <li>Docker Compose multi-service orchestration file</li>
        </ul>
      </div>

      <footer style={{{{ marginTop: '50px', fontSize: '0.85rem', color: '#555555', textAlign: 'center' }}}}>
        Synthesized using Reverse Software Search (RSS) Engine
      </footer>
    </div>
  );
}}
"""

    # 8. Frontend Dockerfile
    frontend_dockerfile = """FROM node:18-alpine AS base

WORKDIR /app

COPY package.json ./
RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
"""

    return {
        "README.md": readme,
        "docker-compose.yml": docker_compose,
        "backend/Dockerfile": backend_dockerfile,
        "backend/requirements.txt": backend_reqs,
        "backend/main.py": backend_main,
        "frontend/package.json": frontend_package,
        "frontend/src/app/page.tsx": frontend_page,
        "frontend/Dockerfile": frontend_dockerfile
    }

def create_zip_archive(files: Dict[str, str]) -> bytes:
    """
    Produce a zipped byte-buffer containing the synthesized codebase folders.
    """
    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zip_file:
        for file_path, content in files.items():
            zip_file.writestr(file_path, content)
    return zip_buffer.getvalue()
